### PR TITLE
New Layer Visualise Tab

### PR DESCRIPTION
**Pull request by MaxLenormand**
Goals:
- [x] Make `Layer Styling` tab more friendly to people not familiar with DeckGL (yours truly)
- [ ] Explain `hasProp` 
- [x] Integrate app `iFrame` directly in example to nudge users to try it out themselves in the app
- [x] Collapsable examples of more in depth parameters

### CODE REVIEW

**Comment by MaxLenormand** [comment]
1 thing I'm not sure about: Is it an issue to have 2 `iframes`?

In short the `viz-styling.mdx` page now has:
```
# Showing Public UDF example
<iframe
  src="https://www.fused.io/public/UDF_Overture_Maps_Example"
  style={{ width: '100%', height: '500px', border: 'none' }}
  title="Overture Maps Example"
/>

# Showing H3 expample
<iframe
  src="/img/deckgl_h3.html"
  height="400px"
  width="100%"
  scrolling="no"
></iframe>
```

I'm not quite sure if that's a problem?

**Comment by isaacbrodsky** [comment]
> 1 thing I'm not sure about: Is it an issue to have 2 `iframes`?
> 
> In short the `viz-styling.mdx` page now has:
> 
> ```
> # Showing Public UDF example
> <iframe
>   src="https://www.fused.io/public/UDF_Overture_Maps_Example"
>   style={{ width: '100%', height: '500px', border: 'none' }}
>   title="Overture Maps Example"
> />
> 
> # Showing H3 expample
> <iframe
>   src="/img/deckgl_h3.html"
>   height="400px"
>   width="100%"
>   scrolling="no"
> ></iframe>
> ```
> 
> I'm not quite sure if that's a problem?

We have had problems with this for showing multiple apps specifically, because on mobile browser it runs out of memory and kills the tab. Showing only one workbench iframe and something else may be fine, as long as the other iframe isn't too heavy.

**Comment by MaxLenormand** [comment]
Thanks for the quick answer Isaac, appreciate it!

Locally this isn't a problem, I'll see how it behaves on the staging deployment and this if looks good I'll ship this

**Comment by MaxLenormand** [comment]
2 `iframes` are working well on `staging` & localhost, shipping this for now even if I haven't added `hasProp` as I still don't fully understand that

**Pull request merged**
